echo "기본 항목을 보호합니다 - izure"

chmod 444 ./data/text/AliasPageNames
chmod 444 ./data/text/AttachmentMacro
chmod 444 ./data/text/BadContent
chmod 444 ./data/text/BlogArchivesMacro
chmod 444 ./data/text/BlogCategoriesMacro
chmod 444 ./data/text/BlogChanges
chmod 444 ./data/text/BlogChangesMacro
chmod 444 ./data/text/CalendarMacro
chmod 444 ./data/text/CategoryCategory
chmod 444 ./data/text/CategoryEmpty
chmod 444 ./data/text/CategoryHomepage
chmod 444 ./data/text/CategoryMacro
chmod 444 ./data/text/CategorySoftwareTool
chmod 444 ./data/text/CategoryTemplate
chmod 444 ./data/text/CommentMacro
chmod 444 ./data/text/DateTimeMacro
chmod 444 ./data/text/DeleteThisPage
chmod 444 ./data/text/DisqusCommentsMacro
chmod 444 ./data/text/DrawMacro
chmod 444 ./data/text/DueDateMacro
chmod 444 ./data/text/DynamicMacro
chmod 444 ./data/text/EditTextForm
chmod 444 ./data/text/FastSearchMacro
chmod 444 ./data/text/FindPage
chmod 444 ./data/text/FootNoteMacro
chmod 444 ./data/text/FortuneCookies
chmod 444 ./data/text/FortuneMacro
chmod 444 ./data/text/FortunePlugin
chmod 444 ./data/text/FullSearchMacro
chmod 444 ./data/text/HelpContents
chmod 444 ./data/text/HelpForBeginners
chmod 444 ./data/text/HelpForDevelopers
chmod 444 ./data/text/HelpIndex
chmod 444 ./data/text/HelpMiscellaneous
chmod 444 ./data/text/HelpOnActions
chmod 444 ./data/text/HelpOnAdministration
chmod 444 ./data/text/HelpOnBasicTextFormatting
chmod 444 ./data/text/HelpOnConfiguration
chmod 444 ./data/text/HelpOnCvsInstallation
chmod 444 ./data/text/HelpOnEditing
chmod 444 ./data/text/HelpOnFormatting
chmod 444 ./data/text/HelpOnGitInstallation
chmod 444 ./data/text/HelpOnHeadlines
chmod 444 ./data/text/HelpOnInstallation
chmod 444 ./data/text/HelpOnInstallation_2fMultipleUser
chmod 444 ./data/text/HelpOnInstallation_2fSetGid
chmod 444 ./data/text/HelpOnInstalling
chmod 444 ./data/text/HelpOnLinking
chmod 444 ./data/text/HelpOnLists
chmod 444 ./data/text/HelpOnLists_2fDev
chmod 444 ./data/text/HelpOnMacros
chmod 444 ./data/text/HelpOnNameSpace
chmod 444 ./data/text/HelpOnNavigation
chmod 444 ./data/text/HelpOnPageCreation
chmod 444 ./data/text/HelpOnPageDeletion
chmod 444 ./data/text/HelpOnProcessingInstructions
chmod 444 ./data/text/HelpOnProcessors
chmod 444 ./data/text/HelpOnRules
chmod 444 ./data/text/HelpOnSmileys
chmod 444 ./data/text/HelpOnSpellCheck
chmod 444 ./data/text/HelpOnSubPages
chmod 444 ./data/text/HelpOnSubPages_2fSubPages
chmod 444 ./data/text/HelpOnTables
chmod 444 ./data/text/HelpOnUpdating
chmod 444 ./data/text/HelpOnUserPreferences
chmod 444 ./data/text/HelpOnVariables
chmod 444 ./data/text/HelpOnXmlPages
chmod 444 ./data/text/HelpTemplate
chmod 444 ./data/text/HomepageTemplate
chmod 444 ./data/text/IncludeMacro
chmod 444 ./data/text/InlineMacro
chmod 444 ./data/text/InterMap
chmod 444 ./data/text/InterMapIcon
chmod 444 ./data/text/InterWiki
chmod 444 ./data/text/InterWikiIcons
chmod 444 ./data/text/IsbnMacro
chmod 444 ./data/text/IsbnMap
chmod 444 ./data/text/MediaMacro
chmod 444 ./data/text/MoniWiki_2fHotKeys
chmod 444 ./data/text/MoniWikiACL
chmod 444 ./data/text/MoniWikiOptions
chmod 444 ./data/text/MoniWikiPlugins
chmod 444 ./data/text/MoniWikiProcessor
chmod 444 ./data/text/MoniWikiTutorial
chmod 444 ./data/text/OekakiMacro
chmod 444 ./data/text/OrphanedPagesMacro
chmod 444 ./data/text/PageHitsMacro
chmod 444 ./data/text/PageListMacro
chmod 444 ./data/text/PatternTemplate
chmod 444 ./data/text/PlayMacro
chmod 444 ./data/text/PluginInfoMacro
chmod 444 ./data/text/RandomPageMacro
chmod 444 ./data/text/RandomQuoteMacro
chmod 444 ./data/text/RecentChanges
chmod 444 ./data/text/RecentChangesMacro
chmod 444 ./data/text/SystemInfo
chmod 444 ./data/text/TableOfContentsMacro
chmod 444 ./data/text/TitleIndex
chmod 444 ./data/text/UploadedFiles
chmod 444 ./data/text/UploadFileMacro
chmod 444 ./data/text/UrlMappingMacro
chmod 444 ./data/text/UserPreferences
chmod 444 ./data/text/VoteMacro
chmod 444 ./data/text/WikiSandBox
chmod 444 ./data/text/WikiSlide
chmod 444 ./data/text/WikiWikiWeb
chmod 444 ./data/text/WordIndex

echo "작업이 끝났습니다"